name: Deploy to IBM Cloud

on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 19 * * 6"
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: |
       
        touch `date +%Y%m%d%H%M%S`
        
        
        cat > manifest-test.yml << EOF
        ---
        applications:
        - name: chickgo
          memory: 128M
          disk_quota: 128M
          random-route: true
          command: 
          buildpacks:
          - binary_buildpack
        EOF
    
    - uses: citizen-of-planet-earth/cf-cli-action@v1
      with:
        cf_api: https://api.us-south.cf.cloud.ibm.com
        cf_username: ${{ secrets.CF_USER_IBM }}
        cf_password: ${{ secrets.CF_PASSWORD_IBM }}
        cf_org: ${{ secrets.CF_ORG_IBM }}
        cf_space: ${{ secrets.CF_SPACE_IBM }}
        command: >
          push chickgo -f manifest-test.yml
